name: delete opened issue
on:
  workflow_dispatch:
    inputs:
      input:
        description: "Test"
        required: false
        default: "World"
jobs:
  delete-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: vtcaregorodtcev/delete-issue@main
        with:
          env: GITHUB_TOKEN: ${{ secrets.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 }}
          issue_node_id: ${{ github.event.issue.node_id }}
