name: delete opened issue
on:
  workflow_dispatch:
    inputs:
      input:
        description: "Test"
        required: false
        default: "World"
jobs:
  delete-issue:
    if: github.event.issue.user.login == 'tensioncore'
    runs-on: ubuntu-latest
    steps:
      - uses: vtcaregorodtcev/delete-issue@main
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          issue_node_id: ${{ github.event.issue.node_id }}
