name: delete opened issue
on:
  workflow_dispatch:
    inputs:
      input:
        description: "Test"
        required: false
        default: "World"
jobs:
  delete-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: vtcaregorodtcev/delete-issue@main
        with:
          github_token: ${{ secrets.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 }}
          issue_node_id: ${{ github.event.issue.node_id }}
